### ISSUE TITLE
After active EL2, PCIe devices load failed

### ISSUE THREAD

**Issue by CoiaPrant233** [TravMurav/slbounce#2]
After active EL2, PCIe devices load failed
Known include WIFI, NVMe, GPU.

Directly boot from NVMe is impossible, so please use USB Disk.

[dmesg](https://github.com/TravMurav/Qcom-Secure-Launch/files/14415559/dmesg.txt)
[lspci -vv](https://github.com/TravMurav/Qcom-Secure-Launch/files/14415564/pci.txt)

**Comment by TravMurav** [comment]
Hi, Linux is generally out of scope for this repo, as mentioned in the readme.

One needs to fix Linux to be able to use pcie on sc8280xp; you can check @jglathe 's work though: https://github.com/jglathe/linux_ms_dev_kit/tree/jg/el2-hackery

**Comment by TravMurav** [comment]
> It seems that the dtbhack just temporarily loads the dtb into the table, is there any permanent way to do it?

Have better firmware :) I.e. Lenovo provides "Linux mode" on x13s that loads the dtb on boot.

dtbhack is, as the name suggests, a hack. Long term it shouldn't exist and will probably be gone.

**Comment by jglathe** [comment]
The jg/el2-iommu-v6.8 branch has video, too. Typing on this box rn.
