### ISSUE TITLE
Add suuport for unfused Android device

### ISSUE THREAD

**Issue by CoiaPrant233** [TravMurav/slbounce#3]
We has some devices for debug. (e.g. QRD845, Dragonboard 845c)
These devices without secure boot. Its can boot any firmware. 
So has any way to set `hyp_secure_launch_enabled` to `1` (using hex editor and qtestsign)
Then we can use slbounce to get EL2.

I think these devices not include mssecapp. We should add a new partition and flash mssecapp.

**Comment by TravMurav** [comment]
SB-off devices should just flash sane firmware and boot linux in el2 directly. If someone wants to enable secure launch on those, they may do as they wish but it will be on them to then provide full woa-like firmware environment to run slbounce.efi

I believe there is nothing slbounce should/can do specifically for android devices.

**Comment by TravMurav** [comment]
You can replace hyp with u-boot on sdm845 et al I believe, in which case you can just boot linux in EL2. There is no reason to dance the secure launch dance if you can replace firmware.

**Comment by TravMurav** [comment]
> I think hyp can not be replace with u-boot. XBL and ABL will not works.

https://www.linaro.org/blog/initial-u-boot-release-for-qualcomm-platforms/

> We want to use android with current boot chain.

You need to customize the bootloader chain regardless. Then, if you think this is the way to go, you may figure out the way to update devcfg and load trustlets from xbl, then run slbounce.efi as is or import it's code into your customized abl, whatever is simpler. (but it's probably simpler to start android from u-boot or otherwise patch the bootloader chain to provide el2 switch callback)

In all the above cases I don't see how slbounce "supporting android" is in scope. There is no retail device that has SL bit set that is not a WoA device, and for sb-off devices it's plain simpler to just fix the firmware.

**Comment by TQSmydreams** [comment]
Hello, I am trying on Android device qrd778, These devices without secure boot
I replaced the tz and hyp partition files of qrd778 with Qualcomm 7280 laptop firmware, but the sltest failed and the device entered 900e. May I ask if this is related to 'mssecapp'?
This is uefilog:
FS4:\> sltest.efi tcblaunch.exe
- 0x27FC01000 [177343] 
SL-Bounce
Running in EL=1
We are FS12:\sltest.efi
Launching using tcblaunch.exe
Allocated 512 pages at 0x7F603000 (TCB)
Loadint PE header with 21504 bytes to 0x7F603000
- Loading section '   .text' with 715264 bytes from offt=0x5400 to 0x7F609000
- Loading section '       CS' with 512 bytes from offt=0xB3E00 to 0x7F6B8000
- Loading section '  .rdata' with 83456 bytes from offt=0xB4000 to 0x7F6B9000
- Loading section '   .data' with 4096 bytes from offt=0xC8600 to 0x7F6CE000
- Loading section '  .pdata' with 14848 bytes from offt=0xC9600 to 0x7F6EA000
- Loading section '   .rsrc' with 1536 bytes from offt=0xCD000 to 0x7F6EE000
- Loading section '  .reloc' with 2048 bytes from offt=0xCD600 to 0x7F6EF000
Security entry at offt 0xCDE00 with size 0x4358
Cert: Len=0x4358, Rev=0x200, Type=0x2
Allocated 35 pages at 0x7FBDE000 (data, cert pages = 5)
TB entrypoint is 0x7FC0585C, Image is at 0x7FC05000, size= 0x2000, data[0]= 0x7FC0E000
Allocated 3 pages at 0x7FC1E000 (bootparams)
Data creation is done. Trying to perform Secure-Launch...
== Available: 0x0
== Auth: 0x0
== Launch: Start EBS        [179415] 
- 0x7F8183F8 [179415] Shell.dll
- 0x9C8D9A24 [179415] CapsuleRuntimeDxe.dll
- 0x9C8DFABC [179415] RealTimeClock.dll
- 0x9CBD90C4 [179415] EmbeddedMonotonicCounter.dll
- 0x9CB38944 [179415] VariableDxe.dll
- 0x9E2D0710 [179415] SdccDxe.dll
- 0x9E31DD08 [179415] ResetRuntimeDxe.dll
- 0x9E3272A0 [179415] RuntimeDxe.dll
- 0x9E7EE790 [179415] SCHandlerRtDxe.dll
- 0x9E7F5EF0 [179415] RscRtDxe.dll
- 0x9E8030A8 [179415] EnvDxe.dll
- 0x7FE2738C [179415] UsbInitDxe.dll
- 0x7FE565AC [179415] UsbMsdDxe.dll
- 0x7FF77C04 [179415] UsbfnDwc3Dxe.dll
- 0x7FF137FC [179415] UsbConfigDxe.dll
- 0x7FFAF4B0 [179415] DisplayDxe.dll
- 0x9C7B67F0 [179415] QcomBds.dll

**Comment by TQSmydreams** [comment]
Hello, I have an Android device qrd778, this device without secure boot
Attempting to flash "tz" and "HYP" from the firmware of the Qualcomm 7280 CLS laptop to qrd778, and then running sltest, the phone crashed and entered Qualcomm 900e. May I ask if it is related to mssecapp? I'm not quite sure why my phone crashed.

This is uefilog:
FS4:\> sltest.efi tcblaunch.exe
- 0x27FC01000 [81532] 
SL-Bounce
Running in EL=1
We are FS12:\sltest.efi
Launching using tcblaunch.exe
Allocated 512 pages at 0x7F603000 (TCB)
Loadint PE header with 21504 bytes to 0x7F603000
- Loading section '   .text' with 715264 bytes from offt=0x5400 to 0x7F609000
- Loading section '       CS' with 512 bytes from offt=0xB3E00 to 0x7F6B8000
- Loading section '  .rdata' with 83456 bytes from offt=0xB4000 to 0x7F6B9000
- Loading section '   .data' with 4096 bytes from offt=0xC8600 to 0x7F6CE000
- Loading section '  .pdata' with 14848 bytes from offt=0xC9600 to 0x7F6EA000
- Loading section '   .rsrc' with 1536 bytes from offt=0xCD000 to 0x7F6EE000
- Loading section '  .reloc' with 2048 bytes from offt=0xCD600 to 0x7F6EF000
Security entry at offt 0xCDE00 with size 0x4358
Cert: Len=0x4358, Rev=0x200, Type=0x2
Allocated 35 pages at 0x7FBDE000 (data, cert pages = 5)
TB entrypoint is 0x7FC0585C, Image is at 0x7FC05000, size= 0x2000, data[0]= 0x7FC0E000
Allocated 3 pages at 0x7FC1E000 (bootparams)
Data creation is done. Trying to perform Secure-Launch...
== Available: 0x0
== Auth: 0x0
== Launch: Start EBS        [83527] 
- 0x7F8183F8 [83527] Shell.dll
- 0x9C8D9A24 [83527] CapsuleRuntimeDxe.dll
- 0x9C8DFABC [83527] RealTimeClock.dll
- 0x9CBD90C4 [83527] EmbeddedMonotonicCounter.dll
- 0x9CB38944 [83527] VariableDxe.dll
- 0x9E2D0710 [83527] SdccDxe.dll
- 0x9E31DD08 [83527] ResetRuntimeDxe.dll
- 0x9E3272A0 [83527] RuntimeDxe.dll
- 0x9E7EE790 [83527] SCHandlerRtDxe.dll
- 0x9E7F5EF0 [83527] RscRtDxe.dll
- 0x9E8030A8 [83527] EnvDxe.dll
- 0x7FE2738C [83527] UsbInitDxe.dll
- 0x7FE565AC [83527] UsbMsdDxe.dll
- 0x7FF77C04 [83527] UsbfnDwc3Dxe.dll
- 0x7FF137FC [83527] UsbConfigDxe.dll
- 0x7FFAF4B0 [83527] DisplayDxe.dll
- 0x9C7B67F0 [83527] QcomBds.dll


This is some data from the CDBBTIM.bin in 900e after the crash, I don't know if it is related to the crash.
0       1.016337 HYP Version Info: QC_IMAGE_VERSION_STRING=TZ.XF.5.11-00559.1-1
0       1.016493 HYP Version Info: IMAGE_VARIANT_STRING=IAGAANAAA
0       1.016626 OEM Version Info: OEM_IMAGE_VERSION_STRING=CRM
0       1.016755 (0)
0       1.019281 hyp_global_consts_init: psci version:00010001
0       1.035280 QUP Private Resource assignment success !!!
0       1.036322 Mapped HLOS Context Bank Aperture Successfully
0       1.036584 ~~~~~HYPX REGISTRATION FAILED~~~~~ Reason: 0xfa11
0       1.072589 first psci cpuon time: 1072588
0      89.703930 hyp_manager_launch: smcParams:0x27f602000 action:0x1
0      89.704012 hyp_manager_launch: status:0x0
0      89.798125 hyp_manager_launch: smcParams:0x27f602000 action:0x2
0      89.798170 hyp_manager_validate_region: Failed region not mapped
0      89.798583 hyp_manager_validate_region: Failed region not mapped
0      89.798836 hyp_manager_lookup_mssecapp_id: qcom.tz.mssecapp APP ID:0x1
0      89.798899 hyp_manager_tzapp_send:  skAction: HYP_IMG_AUTHENTICATE
0      89.799449 hyp_manager_launch: status:0x0
0      89.987942 hyp_manager_launch: smcParams:0x27f602000 action:0x4
0      89.988040 hyp_manager_tzapp_send:  skAction: HYP_IMG_LAUNCH
0      89.988374 hyp_manager_tzapp_send: Mapping 0x64 Memory regions
0      89.988424 hyp_manager_handle_launch: hyp_manager_tzapp_send failed
0      89.989689 Core:0, Data abort from EL2, Translation fault 2nd level
0      89.989736  Write operation
0      89.989758  Faulting Address: 0x27f602000
Address of Last Instruction Executed: 0x80057fcc at EL2
System Registers:
ESR_EL2(96000146)
FAR_EL2(27f602000)
HPFAR_EL2(150000)
ELR_EL2(80057fcc)
HCR_EL2(80080007)
0      89.989921 Making SMC call with ID: TZ_SECURE_WDOG_TRIGGER_ID to ensure the fault is handled
