### ISSUE TITLE
Overlays should (?) have a  `compatible` property

### ISSUE THREAD

**Issue by kuruczgy** [TravMurav/slbounce#8]
Not sure how standard this is, but at least NixOS expects it to exists, because it uses it to know which device trees it can apply the overlay to:
https://github.com/NixOS/nixpkgs/blob/69661586d1c9d85e859887d95285f6fc92521657/pkgs/os-specific/linux/device-tree/apply_overlays.py#L87

I had to add the following to get it working:

```diff
diff --git a/dtbo/x1e-el2.dtso b/dtbo/x1e-el2.dtso
index e9fce06..97567fc 100644
--- a/dtbo/x1e-el2.dtso
+++ b/dtbo/x1e-el2.dtso
@@ -7,6 +7,10 @@
 /dts-v1/;
 /plugin/;

+/ {
+       compatible = "qcom,x1e80100";
+};
+
 &{/} {
        chosen {
                dtbhack-el2-overlay = "x1e-el2";
```

Unless this causes some issues I think it would be nice to have this for all of the overlays.

**Comment by TravMurav** [comment]
Interesting... I don't exactly believe this is a "specification" since I don't think this is explicitly defined anywhere, but I guess libfdt will ignore anything in / anyway so it won't hurt...

**Comment by TravMurav** [comment]
quick look at https://github.com/radxa/overlays/blob/main/arch/arm64/boot/dts/rockchip/overlays/audioinjector-isolated-soundcard.dts suggests that this is a part of "wild west" of random vendor extensions to me...

**Comment by TravMurav** [comment]
fixed in https://github.com/TravMurav/slbounce/commit/97b24ec89faa11827e7def220b0aa53dd5d5f447
